### ISSUE TITLE
Add ability to cancel orders

### ISSUE THREAD

**Issue by davidvhill** [USGS-EROS/espa-web#41]
Users should be able to cancel their own orders.  This will require finding any items that are currently in the hadoop queue and killing the hadoop job, resetting the database for any items that were grouped in that job but still need to be run (multiple users/orders are in each hadoop job), and removing any completed items from the online cache.  Will also need a new status 'cancelled' for orders + products.

**Comment by raulpoppiel** [comment]
We need an option to cancel orders, urgently!

**Comment by jakebrinkmann** [comment]
Hi @raulpoppiel, today we've added (in #78) the ability for users to cancel each of their in-progress orders. Thanks for your feedback!

**Comment by raulpoppiel** [comment]
Thank you so much @jakebrinkmann for this option!! Will be very useful.
