### ISSUE TITLE
"LST" missing from "Requested Processing" field on Order Status page

### ISSUE THREAD

**Issue by sfoga-usgs** [USGS-EROS/espa-web#49]
If Land Surface Temperature (LST) is ordered through ESPA staff page, it is not listed in the "Requested Proecssing" field. See example image of an LST order (with no other processing options). 
![lst_missing](https://cloud.githubusercontent.com/assets/12802444/11755573/d8753cf8-a018-11e5-9eda-ffd263342a69.PNG)

**Comment by dhill-usgs** [comment]
what environment

On Fri, Dec 11, 2015 at 3:07 PM, Steve Foga <notifications@github.com>
wrote:

> If Land Surface Temperature (LST) is ordered through ESPA staff page, it
> is not listed in the "Requested Proecssing" field See example image of an
> LST order (with no other processing options)
> [image: lst_missing]
> <https://camo.githubusercontent.com/f91fd9cb075e9b6774911e5c75aa4b2b2b7329fa/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31323830323434342f31313735353537332f64383735336366382d613031382d313165352d396564612d666664323633333432613639504e47>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-web/issues/49>.
>



-- 
David V. Hill
LSRD
SGT
Contractor to USGS Earth Resources Observation And Science Center (EROS)
47914 252nd Street
Sioux Falls, SD 57198-9801
605.594.2639
dhill@usgs.gov

**Comment by sfoga-usgs** [comment]
tst and prd

On Fri, Dec 11, 2015 at 3:11 PM, David V. Hill <notifications@github.com>
wrote:

> what environment
>
> On Fri, Dec 11, 2015 at 3:07 PM, Steve Foga <notifications@github.com>
> wrote:
>
> > If Land Surface Temperature (LST) is ordered through ESPA staff page, it
> > is not listed in the "Requested Proecssing" field See example image of an
> > LST order (with no other processing options)
> > [image: lst_missing]
> > <
> https://camo.githubusercontent.com/f91fd9cb075e9b6774911e5c75aa4b2b2b7329fa/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31323830323434342f31313735353537332f64383735336366382d613031382d313165352d396564612d666664323633333432613639504e47
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGS-EROS/espa-web/issues/49>.
> >
>
>
>
> --
> David V. Hill
> LSRD
> SGT
> Contractor to USGS Earth Resources Observation And Science Center (EROS)
> 47914 252nd Street
> Sioux Falls, SD 57198-9801
> 605.594.2639
> dhill@usgs.gov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-web/issues/49#issuecomment-164048560>.
>



-- 
Steven Foga
Remote Sensing Scientist
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD  57198
(605) 594-2839
sfoga@usgs.gov

**Comment by dhill-usgs** [comment]
This is for the LABEL that shows the requested processing levels only.

On Fri, Dec 11, 2015 at 3:16 PM, Steve Foga <notifications@github.com>
wrote:

> tst and prd
>
> On Fri, Dec 11, 2015 at 3:11 PM, David V. Hill <notifications@github.com>
> wrote:
>
> > what environment
> >
> > On Fri, Dec 11, 2015 at 3:07 PM, Steve Foga <notifications@github.com>
> > wrote:
> >
> > > If Land Surface Temperature (LST) is ordered through ESPA staff page,
> it
> > > is not listed in the "Requested Proecssing" field See example image of
> an
> > > LST order (with no other processing options)
> > > [image: lst_missing]
> > > <
> >
> https://camo.githubusercontent.com/f91fd9cb075e9b6774911e5c75aa4b2b2b7329fa/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31323830323434342f31313735353537332f64383735336366382d613031382d313165352d396564612d666664323633333432613639504e47
> > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/USGS-EROS/espa-web/issues/49>.
> > >
> >
> >
> >
> > --
> > David V. Hill
> > LSRD
> > SGT
> > Contractor to USGS Earth Resources Observation And Science Center (EROS)
> > 47914 252nd Street
> > Sioux Falls, SD 57198-9801
> > 605.594.2639
> > dhill@usgs.gov
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGS-EROS/espa-web/issues/49#issuecomment-164048560
> >.
> >
>
>
>
> --
> Steven Foga
> Remote Sensing Scientist
> Stinger Ghaffarian Technologies (SGT, Inc.)
> Contractor to the U.S. Geological Survey (USGS)
> Earth Resources Observation and Science (EROS) Center
> 47914 252nd Street
> Sioux Falls, SD 57198
> (605) 594-2839
> sfoga@usgs.gov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-web/issues/49#issuecomment-164049391>.
>



-- 
David V. Hill
LSRD
SGT
Contractor to USGS Earth Resources Observation And Science Center (EROS)
47914 252nd Street
Sioux Falls, SD 57198-9801
605.594.2639
dhill@usgs.gov

**Comment by dhill-usgs** [comment]
This has been corrected.
