### ISSUE TITLE
Increase maximum grid size beyond 100M

### ISSUE THREAD

**Issue by sfoga-usgs** [USGS-EROS/espa-web#50]
Users are finding the new maximum grid size of 100 million (10k by 10k) is not meeting their needs. One user expressed that a maximum of at least ~167 million is necessary to deliver data in an acceptable format.

**Comment by klsmith-usgs** [comment]
I would like to see the justification on that one. I suspect it has to do
with standard framing extents some of the projects are doing, or at least
thinking about. If it is that, then I might have an alternative in mind.

On Tue, Dec 15, 2015 at 8:21 AM, Steve Foga <notifications@github.com>
wrote:

> Users are finding the new maximum grid size of 100 million (10k by 10k) is
> not meeting their needs One user expressed that a maximum of at least 166
> million is necessary to deliver data in an acceptable format
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-web/issues/50>.
>



-- 
Kelcy Smith
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd St
Sioux Falls, South Dakota 57198
Office: (605) 594-2836
Fax: (605) 594-6529
Email: klsmith@usgs.gov

**Comment by dhill-usgs** [comment]
it's been increased to 200 million.
